### PR TITLE
feat: add ESLint cesium config

### PR DESCRIPTION
**Pull request by EnzoVieira**
In this PR, I added the CeSIUM eslint config and needed to remove the other lint packages for compatibility purposes. Also, I removed the CI prettier check since the ESLint config uses the prettier plugin (if we have prettier plugin and prettier lib in the same project, this may cause compatibility issues and could become a redundant check).

### CODE REVIEW

**Comment by RuiL1904** [comment]
If the formatting check was removed, how will we ensure that the code is formatted?
@EnzoVieira

**Comment by EnzoVieira** [comment]
> If the formatting check was removed, how will we ensure that the code is formatted? @EnzoVieira

Cause the cesium ESLint config now use the prettier plugin (so prettier became ESLint rules) and if `npm run lint` passes, it means that prettier rules passes too. This plugin also automatically format the code on save. You can see in [plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) where it says:

> "Runs [Prettier](https://github.com/prettier/prettier) as an [ESLint](https://eslint.org/) rule and reports differences as individual ESLint issues."

**Comment by afonsopimenta** [comment]
> Cause the cesium ESLint config now use the prettier plugin (so prettier became ESLint rules) and if `npm run lint` passes, it means that prettier rules passes too. This plugin also automatically format the code on save. You can see in [plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) where it says:
> 
> > "Runs [Prettier](https://github.com/prettier/prettier) as an [ESLint](https://eslint.org/) rule and reports differences as individual ESLint issues."

The command `npm run lint:fix` is removing all semicolons from the line ends. Is this the intended behaviour? And if so, it does not match the behaviour of `npm run format` which writes back all the semicolons.

**Comment by EnzoVieira** [comment]
> > Cause the cesium ESLint config now use the prettier plugin (so prettier became ESLint rules) and if `npm run lint` passes, it means that prettier rules passes too. This plugin also automatically format the code on save. You can see in [plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) where it says:
> > > "Runs [Prettier](https://github.com/prettier/prettier) as an [ESLint](https://eslint.org/) rule and reports differences as individual ESLint issues."
> 
> The command `npm run lint:fix` is removing all semicolons from the line ends. Is this the intended behaviour? And if so, it does not match the behaviour of `npm run format` which writes back all the semicolons.

Yes it is the intended behaviour, but if we would like to change it we can disable this eslint rule for this repo or change it in our plugin. We have to discuss this rule. Also, coming back with `prettier.config.js` and rewrite with the same eslint rules should be the correct approach, my bad.

What do you guys think about this? @RuiL1904 @afonsopimenta

**Comment by afonsopimenta** [comment]
[Typescript ESLint](https://typescript-eslint.io/linting/troubleshooting/formatting/) is against using lintersfor formatting files since 2020, and from the research I've done I agree with them. I like the idea of having a default lint config for every cesium repo but i think formatting should be kept separate. Maybe we can also create a repo for a default format config across all our repos?

**Comment by EnzoVieira** [comment]
> [Typescript ESLint is against using linters for formatting](https://typescript-eslint.io/linting/troubleshooting/formatting/) files since 2020, and from the research I've done I agree with them.
> 
> I like the idea of having a default lint config for every cesium repo but i think formatting should be kept separate. Maybe we can also create a repo for a default format config across all our repos?
> 
> What's your opinion? @RuiL1904 @EnzoVieira

Totally agree with you! But reading this article you sent, it says: 

> If you see formatting rules enabled in your ESLint configuration, we recommend using [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) to disable formatting rules in your ESLint configuration. You can then configure your formatter separately from ESLint.

our plugin is already using this eslint-prettier-config to disable formatting rules. Something we can change in our plugin is that we are configuring the prettier with [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) (that is another lib that runs prettier as an ESLint rule) and put this setting separately from eslint. What do you think?

**Comment by EnzoVieira** [comment]
Our VSCode is probably formatting the code with eslint because we have the configuration in global `settings.json`

```
  "editor.codeActionsOnSave": [
    "source.fixAll.eslint"
  ],
```

**Comment by afonsopimenta** [comment]
I'm in favour of discarding the `elsint-plugin-prettier` since it seems to not be able to have pettier plugins added to it like `prettier-plugin-tailwindcss`

**Comment by RuiL1904** [comment]
@EnzoVieira Could you TL;DR the conversation? What are the options we have?

**Comment by afonsopimenta** [comment]
> Yes we have support for prettier plugin, like the [eslint-plugin-tailwindcss](https://github.com/francoismassart/eslint-plugin-tailwindcss) that we use in our plugin and its built on top of `prettier-plugin-tailwindcss`. We can still disattach the prettier from the plugin, but we have to discard all the prettier related plugins.
> 
> 
> 
> Lets see what people think @RuiL1904 @MarioRodrigues10 @GresosJ @ruioliveira02 @diogogmatos 

- I didn't realise `eslint-plugin-tailwindcss` was on the repo, from the testing I've done it does not seem to be working, it doesn't sort the tailwind classes properly. 

For example, for `className="grid-cols-2 grid` the expected behaviour would be to rewrite it as `className="grid grid-cols-2` and it just keeps it the same, the opposite also maintains the class order.

As long as we can fix this issue, I don't mind having the linter format the doucments.

**Comment by EnzoVieira** [comment]
> @EnzoVieira Could you TL;DR the conversation? What are the options we have?

Our ESLint plugin is using the prettier, so, our formatting rules are coupled to the ESLint. We have two options: 

1. detach the prettier related plugins and make CeSIUM's own prettier config/plugin
2. maintain this rules and rewrite the `prettier.config.js` with the same rules we use in eslint plugin to run `npm run format` with the same behaviour as `npm run lint:fix`

**Comment by EnzoVieira** [comment]
> > Yes we have support for prettier plugin, like the [eslint-plugin-tailwindcss](https://github.com/francoismassart/eslint-plugin-tailwindcss) that we use in our plugin and its built on top of `prettier-plugin-tailwindcss`. We can still disattach the prettier from the plugin, but we have to discard all the prettier related plugins.
> > Lets see what people think @RuiL1904 @MarioRodrigues10 @GresosJ @ruioliveira02 @diogogmatos
> 
> I didn't realise `eslint-plugin-tailwindcss` was on the repo, from the testing I've done it does not seem to be working, it doesn't sort the tailwind classes properly.
> 
> For example, for `className="grid-cols-2 grid` the expected behaviour would be to rewrite it as `className="grid grid-cols-2` and it just keeps it the same, the opposite also maintains the class order.
> 
> As long as we can fix this issue, I don't mind having the linter format the doucments.

It does sort the classnames for me 🤔, maybe our global `settings.json` are different or do you have the eslint vscode extension?

**Comment by afonsopimenta** [comment]
> > @EnzoVieira Could you TL;DR the conversation? What are the options we have?
> 
> 
> 
> Our ESLint plugin is using the prettier, so, our formatting rules are coupled to the ESLint. We have two options: 
> 
> 
> 
> 1. detach the prettier related plugins and make CeSIUM's own prettier config/plugin
> 
> 2. maintain this rules and rewrite the `prettier.config.js` with the same rules we use in eslint plugin to run `npm run format` with the same behaviour as `npm run lint:fix`
> 
> 
> 
> is that right? @afonsopimenta 

Yes, just to give context to why coupling linting with formatting might not the best idea you can read [this article](https://typescript-eslint.io/linting/troubleshooting/formatting/)

**Comment by RuiL1904** [comment]
I like the option of having a CeSIUM's prettier config - it would lead to a more concise and coherent styling throughout our repos. Are you willing to go with this choice? @EnzoVieira @afonsopimenta

**Comment by afonsopimenta** [comment]
> It does sort the classnames for me 🤔, maybe our global `settings.json` are different or do you have the eslint vscode extension?

Just tested again and it is indeed sorting them, I must have done something wrong the first time, my bad. @EnzoVieira

**Comment by afonsopimenta** [comment]
> I like the option of having a CeSIUM's prettier config - it would lead to a more concise and coherent styling throughout our repos. Are you willing to go with this choice? @EnzoVieira @afonsopimenta

@RuiL1904 I'm all for it.

**Comment by EnzoVieira** [comment]
> I like the option of having a CeSIUM's prettier config - it would lead to a more concise and coherent styling throughout our repos. Are you willing to go with this choice? @EnzoVieira @afonsopimenta

i'm in favor of it! So i'm putting this PR as draft until the cesium plugins is done.

**Comment by RuiL1904** [comment]
Does any of you want to take care of it, by the way? @EnzoVieira @afonsopimenta

**Comment by afonsopimenta** [comment]
> Does any of you want to take care of it, by the way? @EnzoVieira @afonsopimenta 

@EnzoVieira Can you do it? I'm not yet familiar on how to do an installable config like that.

**Comment by EnzoVieira** [comment]
We can work toghether in this to discuss the rules and helping you to maintain this plugin in the future 🚀, is it okay for you? @afonsopimenta

**Comment by diogogmatos** [comment]
Closed due to integral project changes both in planning and structure, #21

**Pull request closed without merging**
