### PR TITLE
General Improvements

### PR DESCRIPTION
**Pull request by diogogmatos**
Até gostei dos cantos arredondados, mas vejam o que acham. Também gosto normal.

image

### CODE REVIEW

**Review by GresosJ — COMMENTED** [review]
Screenshot_20230923_001020

I feel that the teams page looks kinda weird

**Comment by diogogmatos** [comment]
> Screenshot_20230923_001020
> 
> 
> 
> I feel that the teams page looks kinda weird
> 
> 

I forgot to change that page 😅 I only changed the home page, and I edited the layout paddings so it's affecting all the pages. I'll fix that tomorrow :)

**Comment by GresosJ** [comment]
And I really dont like the rounded corners

**Review by GresosJ — APPROVED** [review]
Everything looks good

**Pull request merged**
