### PR TITLE
feat: use specific font style instead of variable font to improve loading time

### PR DESCRIPTION
**Pull request by diogogmatos**
Self explanatory.

### CODE REVIEW

**Comment by nunom27** [comment]
Maybe we could add the woff2 font found in this link: [https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,300,0..1,0](url). This one is only 395kB and has just the required properties, as far as I'm aware.

**Comment by diogogmatos** [comment]
> Maybe we could add the woff2 font found in this link: [https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,300,0..1,0](url). This one is only 395kB and has just the required properties, as far as I'm aware.

I believe that was exactly the one we had before, right?

**Comment by nunom27** [comment]
> > Maybe we could add the woff2 font found in this link: [https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,300,0..1,0](url). This one is only 395kB and has just the required properties, as far as I'm aware.
> 
> I believe that was exactly the one we had before, right?

The one we had before had all variants in the same woff2 file, however google fonts have the ability to trim down those variants by setting them in the URL parameters. In this case the font would be https://fonts.gstatic.com/s/materialsymbolsoutlined/v210/kJF4BvYX7BgnkSrUwT8OhrdQw4oELdPIeeII9v6oDMzBwG-RpA6RzaxHMPdY40KH8nGzv3fzfVJU22ZZLsYEpzC_1qmr5Y0.woff2 which is much smaller than the TTF version and the previous woff2 version.

**Comment by diogogmatos** [comment]
> > > Maybe we could add the woff2 font found in this link: [https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,300,0..1,0](url). This one is only 395kB and has just the required properties, as far as I'm aware.
> 
> > 
> 
> > I believe that was exactly the one we had before, right?
> 
> 
> 
> The one we had before had all variants in the same woff2 file, however google fonts have the ability to trim down those variants by setting them in the URL parameters. In this case the font would be https://fonts.gstatic.com/s/materialsymbolsoutlined/v210/kJF4BvYX7BgnkSrUwT8OhrdQw4oELdPIeeII9v6oDMzBwG-RpA6RzaxHMPdY40KH8nGzv3fzfVJU22ZZLsYEpzC_1qmr5Y0.woff2 which is much smaller than the TTF version and the previous woff2 version.

Ohh, nice! Let's use that one then. However, we need to keep a TTF version of the font because older/outdated browsers don't yet support woff2.

**Review by nunom27 — APPROVED** [review]
Great!

**Pull request merged**
