### PR TITLE
refactor: new bootstrap

### PR DESCRIPTION
**Pull request by afonsopimenta**

### CODE REVIEW

**Comment by afonsopimenta** [comment]
Any more changes we should add?
I personally believe we should make the TS config more strict, any opinions on that?

**Comment by diogogmatos** [comment]
> Any more changes we should add? I personally believe we should make the TS config more strict, any opinions on that?

I want this project to be as stable and clean as possible, so I'm up for strict TS rules. Don't know if the others agree @ruilopesm @joaodiaslobo @MarioRodrigues10 etc?

**Comment by ruilopesm** [comment]
@diogogmatos Totally agree.

**Comment by joaodiaslobo** [comment]
Makes total sense! @diogogmatos

**Comment by MarioRodrigues10** [comment]
@diogogmatos I agree with you !

**Comment by afonsopimenta** [comment]
PR is ready for review, build and style cs have to be turned off for it to be merged though.
@diogogmatos @ruilopesm @joaodiaslobo @MarioRodrigues10

**Review by diogogmatos — APPROVED** [review]
LGTM

**Pull request merged**
